# Generated by Django 5.1.1 on 2024-09-24 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_auto_20240924_0731"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="subteam",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teams.subteam",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="team",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="teams.team"
            ),
        ),
    ]
